### ISSUE TITLE
registration

### ISSUE THREAD

**Issue by NoufAlh** [kuoa/nearby-chat#33]
for some reasons, i ran the app and once i wanted to register it keep saying " authentication failed", may ik the reason? 
even once i changed the json file to mine, i got many errors. 
please help me to solve the problem, i really need ur project
thanks..

**Comment by FudgeKun** [comment]
Could you solve it? I also need this app and i dont know how to pass the registeration part..

**Comment by W4lspirit** [comment]
Hi @NoufAlh  @FudgeKun ,
This was a school project, so the different api key used are no longer up.
You can modified the file google-service.json with your generated api-key.
https://developers.google.com/android/guides/google-services-plugin

Note that the "authentication failed" message is only shown when trying to sign-in :
- Maybe your firebase credentials are not set correctly.

You can have more information on the error by logging the `task.getResult()` in MainActivity.java: 109

**Comment by FudgeKun** [comment]
@W4lspirit Sorry, i'm very new to android programming, can u explain it? Because i couldn't understand it
